services:
  # after the first time starting ollama, run the following to get models:
  # docker exec -it ollama sh -c 'ollama pull llama3.1:8b-instruct-q4_K_M && ollama pull phi3:mini'

  ollama:
    image: ollama/ollama:0.11.4
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - plotline
    volumes:
      - ollama_data:/root/.ollama
    # restart: unless-stopped

  back:
    build:
      context: ./back
      target: dev
    container_name: back
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    networks:
      - plotline

volumes:
  ollama_data:

networks:
  plotline:
