app:
  env: "prod"
  port: 8080
  read_header_timeout: 5s
  read_timeout: 15s
  write_timeout: 30s
  idle_timeout: 60s

log:
  level: "info"
  format: "json"

ollama:
  base_url: "http://ollama:11434"

valkey:
  address: "valkey:6379"
